### ISSUE TITLE
Jsonp error `Before you use jsonp, please run "npm i -S jsonp-body".   `

### ISSUE THREAD

**Issue by dazjean** [Ursajs/Ursa#5]
```
Error: Before you use jsonp, please run "npm i -S jsonp-body"

    at Function.requireCatch (/home/app/function/node_modules/@ursajs/core/lib/loader/LazyModules.js:10:19)
    at Function.get jsonpBody [as jsonpBody] (/home/app/function/node_modules/@ursajs/core/lib/loader/LazyModules.js:14:28)
    at Object.jsonp (/home/app/function/node_modules/@ursajs/core/lib/extends/Context.js:19:43)
    at jsonp (/home/app/function/node_modules/@ursajs/core/lib/extends/Results.js:27:20)
    at Function.finish (/home/app/function/node_modules/@ursajs/core/lib/core/Result.js:69:52)
    at callMethod (/home/app/function/node_modules/@ursajs/router/lib/router.js:55:30)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
Should it be add to dependencies in frame core modules? but now , i need npm install this dependent in my project package.json

**Comment by EdwardZZZ** [comment]
Add dependencies when using, the purpose is to reduce dependencies, speed up installation, 
and also allow users to control the version by themselves.
